package com.reya.goldenquarry.client;

import com.mojang.blaze3d.systems.RenderSystem;
import com.reya.goldenquarry.GoldenQuarry;
import net.minecraft.Util;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/**
 * The tentacles round the vacuum chest's GUI and the stars they hunt. They are drawn frame by frame
 * by tools/gen_tentacles.py (glossy back with dark spots, pink underside with round suckers, the tip
 * curled; three colourings, each tentacle its own); their roots are under the frame, which is drawn
 * over them.
 * <p>
 * Most of them sway slowly, are drawn in and reach out again, and now and then snap at the air
 * (32 frames a loop, vacuum_chest_tentacles.png). The catchers play an act (vacuum_chest_catchers.png):
 * a star drifts in to the tip, the tentacle lunges and curls round it, drags it into the chest and
 * stays in there a while, comes out again holding it; the star struggles, the tentacle thrashes,
 * the star breaks free in a burst (a ring of light, a shower of little stars, or a flash of rays,
 * by turns) as the tip whips open, and the tentacle snatches after it and misses.
 * More stars drift in round them all: little sparkles, four- and eight-pointed stars, pink, gold, ice blue.
 */
final class Tentacles {
    private static final ResourceLocation SHEET = new ResourceLocation(GoldenQuarry.MODID, "textures/gui/vacuum_chest_tentacles.png");
    private static final ResourceLocation ACTS = new ResourceLocation(GoldenQuarry.MODID, "textures/gui/vacuum_chest_catchers.png");
    private static final ResourceLocation STARS = new ResourceLocation(GoldenQuarry.MODID, "textures/gui/vacuum_chest_stars.png");
    private static final int SIZE = 96, FRAMES = 32, REACH = 40;
    /** One frame of the loop lasts this long: a whole sway, in and out, takes FRAMES of them. */
    private static final long FRAME_MS = 180L;
    /** Root x, y (GUI pixels), direction out, length: as in tools/gen_tentacles.py, in its order. */
    private static final float[][] TENTACLES;
    private static final int[] STAR_RGB = {0xFFD8F0, 0xFFE9A8, 0xC8F0FF};

    static {
        float r = 216 - 1;
        TENTACLES = new float[][]{
                {6, 14, -0.75F, -0.66F, 54}, {34, 13, -0.2F, -0.98F, 40}, {4, 48, -0.98F, -0.2F, 40},
                {4, 104, -0.97F, 0.25F, 46}, {9, 152, -0.8F, 0.6F, 52}, {18, 160, -0.4F, 0.92F, 40},
                {r - 6, 14, 0.75F, -0.66F, 54}, {r - 34, 13, 0.2F, -0.98F, 40}, {r - 4, 48, 0.98F, -0.2F, 40},
                {r - 4, 104, 0.97F, 0.25F, 46}, {r - 9, 152, 0.8F, 0.6F, 52}, {r - 18, 160, 0.4F, 0.92F, 40}};
    }

    // <generated by tools/gen_tentacles.py>
    /** Whether each tentacle catches stars (it is in the catchers' sheet then), and its row in its sheet. */
    private static final boolean[] CATCHER = {true, false, false, true, false, false, false, true, false, false, true, false};
    private static final int[] ROW = {0, 0, 1, 1, 2, 3, 4, 2, 5, 6, 3, 7};
    private static final int OTHERS = 8, CATCHERS = 4;
    /** The catchers' act: how long each frame lasts, and what the star is doing in it. */
    private static final int[] ACT_MS = {200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 55, 55, 55, 55, 55, 55, 110, 110, 110, 110, 110, 110, 110, 110, 1400, 110, 110, 110, 110, 110, 110, 90, 90, 90, 90, 90, 90, 90, 90, 60, 60, 60, 160, 160, 160, 160};
    private static final int[] ACT_STATE = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5};
    /** Where each catcher's star is in each frame (sprite pixels). */
    private static final int[][][] ACT_STAR = {
            {{57, 15}, {58, 16}, {59, 17}, {60, 18}, {61, 20}, {62, 22}, {63, 24}, {64, 25}, {65, 27}, {66, 30}, {68, 32}, {69, 34}, {69, 34}, {69, 34}, {69, 34}, {69, 34}, {69, 34}, {69, 34}, {69, 35}, {68, 38}, {69, 42}, {70, 47}, {72, 53}, {74, 61}, {77, 70}, {78, 74}, {78, 74}, {76, 70}, {73, 63}, {71, 58}, {70, 54}, {69, 51}, {69, 49}, {68, 48}, {65, 50}, {69, 53}, {70, 48}, {66, 47}, {67, 54}, {68, 48}, {70, 50}, {62, 43}, {61, 40}, {59, 37}, {57, 33}, {54, 29}, {52, 24}, {49, 20}},
            {{41, 70}, {42, 69}, {43, 69}, {45, 68}, {46, 67}, {48, 66}, {50, 65}, {52, 63}, {54, 62}, {56, 61}, {58, 59}, {60, 58}, {60, 58}, {60, 58}, {60, 58}, {60, 58}, {60, 58}, {60, 58}, {61, 57}, {63, 57}, {65, 55}, {69, 52}, {73, 49}, {78, 45}, {84, 40}, {86, 38}, {86, 38}, {85, 40}, {80, 45}, {76, 49}, {72, 51}, {70, 52}, {70, 52}, {71, 51}, {71, 55}, {70, 53}, {69, 50}, {71, 52}, {73, 53}, {67, 54}, {71, 49}, {63, 56}, {60, 58}, {58, 60}, {54, 62}, {49, 65}, {45, 68}, {41, 71}},
            {{65, 50}, {64, 51}, {64, 53}, {63, 54}, {62, 56}, {61, 57}, {60, 59}, {59, 61}, {58, 63}, {57, 65}, {55, 68}, {54, 70}, {54, 70}, {54, 70}, {54, 70}, {54, 70}, {54, 70}, {54, 70}, {54, 69}, {53, 70}, {52, 71}, {51, 73}, {48, 76}, {45, 80}, {41, 85}, {40, 87}, {40, 87}, {41, 86}, {44, 81}, {47, 77}, {49, 75}, {51, 74}, {52, 73}, {53, 72}, {50, 71}, {50, 74}, {54, 73}, {53, 71}, {48, 73}, {53, 72}, {53, 74}, {55, 66}, {56, 63}, {58, 60}, {61, 56}, {63, 52}, {66, 48}, {68, 43}},
            {{76, 30}, {75, 30}, {74, 30}, {72, 29}, {70, 28}, {69, 28}, {67, 27}, {64, 26}, {62, 26}, {60, 25}, {58, 24}, {55, 23}, {55, 23}, {55, 23}, {55, 23}, {55, 23}, {55, 23}, {55, 23}, {54, 24}, {51, 25}, {48, 25}, {43, 26}, {37, 26}, {29, 25}, {20, 24}, {16, 24}, {16, 24}, {20, 24}, {27, 25}, {34, 26}, {38, 28}, {40, 29}, {40, 29}, {39, 29}, {42, 26}, {41, 28}, {40, 31}, {41, 28}, {39, 26}, {45, 31}, {38, 30}, {48, 32}, {51, 33}, {55, 34}, {59, 36}, {64, 37}, {69, 39}, {74, 40}},
    };
    // </generated>

    private static final int ACT_TOTAL;
    private static final int[] ACT_START;

    static {
        ACT_START = new int[ACT_MS.length];
        int t = 0;
        for (int i = 0; i < ACT_MS.length; i++) {
            ACT_START[i] = t;
            t += ACT_MS[i];
        }
        ACT_TOTAL = t;
    }

    void draw(GuiGraphics g, int left, int top) {
        long now = Util.getMillis();
        drifting(g, left, top, now);
        for (int i = 0; i < TENTACLES.length; i++) {
            float[] tc = TENTACLES[i];
            int ox = Math.round(tc[0] - (SIZE / 2.0F - REACH * tc[2]));
            int oy = Math.round(tc[1] - (SIZE / 2.0F - REACH * tc[3]));
            if (CATCHER[i]) {
                act(g, left, top, i, ox, oy, now);
            } else {
                int frame = (int) ((now / FRAME_MS + i * 7L) % FRAMES);
                g.blit(SHEET, left + ox, top + oy, frame * SIZE, ROW[i] * SIZE, SIZE, SIZE, SIZE * FRAMES, SIZE * OTHERS);
            }
        }
    }

    /** Stars drifting in round the tentacles, faster as they get near, fading in far out. */
    private static void drifting(GuiGraphics g, int left, int top, long now) {
        double t = now / 1000.0D;
        for (int k = 0; k < 26; k++) {
            float[] tc = TENTACLES[k % TENTACLES.length];
            double speed = 0.12D + (k * 37 % 10) * 0.012D;
            double p = (t * speed + k * 0.37D) % 1.0D;
            double side = ((k * 7) % 5 - 2) * 5.0D + (k % 3 - 1) * 2.0D;
            double far = tc[4] * (0.8D + (k % 4) * 0.12D);
            double sx = tc[0] + tc[2] * far - tc[3] * side, sy = tc[1] + tc[3] * far + tc[2] * side;
            double ex = tc[0] - tc[2] * 4.0D, ey = tc[1] - tc[3] * 4.0D;
            double e = Math.pow(p, 1.6D);
            int kind = k % 3 == 0 ? 2 : k % 3 == 1 ? 0 : 1;
            star(g, left + (int) Math.round(sx + (ex - sx) * e), top + (int) Math.round(sy + (ey - sy) * e),
                    kind, (k / 3) % 3, (int) ((now / (120L + k % 4 * 30L) + k) % 8), (float) Math.min(1.0D, p / 0.25D));
        }
    }

    /** A catcher's act: its frame, and its star doing what the act says. */
    private static void act(GuiGraphics g, int left, int top, int i, int ox, int oy, long now) {
        int c = ROW[i];
        long shifted = now + c * 1811L;
        long round = shifted / ACT_TOTAL;                      // which time round: the burst changes each time
        int t = (int) (shifted % ACT_TOTAL);
        int f = 0;
        while (f + 1 < ACT_MS.length && ACT_START[f + 1] <= t) f++;
        float frac = (t - ACT_START[f]) / (float) ACT_MS[f];
        g.blit(ACTS, left + ox, top + oy, f * SIZE, c * SIZE, SIZE, SIZE, SIZE * ACT_MS.length, SIZE * CATCHERS);
        int state = ACT_STATE[f];
        if (state == 0) return;
        int[] here = ACT_STAR[c][f];
        int next = (f + 1) % ACT_MS.length;
        float x = here[0], y = here[1];
        if (ACT_STATE[next] != 0 && next != 0) {               // glide to the next frame's place
            x += (ACT_STAR[c][next][0] - here[0]) * frac;
            y += (ACT_STAR[c][next][1] - here[1]) * frac;
        }
        int colour = (int) ((round + c) % 3);
        int sx = left + ox + Math.round(x), sy = top + oy + Math.round(y);
        switch (state) {
            case 1 -> star(g, sx, sy, 2, colour, (int) ((now / 140L) % 8), f < 2 ? (f + frac) / 2.0F : 1.0F);
            case 2 -> star(g, sx, sy, 2, colour, 3 + (int) ((now / 200L) % 2), 1.0F);
            case 3 -> {                                        // struggling: shaking, flickering, throwing sparks
                int jx = (int) (hash(now / 70L + c) % 3) - 1, jy = (int) (hash(now / 70L + c + 99) % 3) - 1;
                star(g, sx + jx, sy + jy, 2, colour, 2 + (int) ((now / 60L) % 4), 1.0F);
                for (int k = 0; k < 3; k++) {
                    long h = hash(now / 90L * 7 + k + c * 13);
                    float life = (now % 90L) / 90.0F;
                    int px = sx + (int) (h % 9) - 4, py = sy + (int) ((h >> 8) % 9) - 4;
                    g.fill(px, py, px + 1, py + 1, alpha(1.0F - life) | STAR_RGB[colour]);
                }
            }
            default -> {                                       // breaking free and fleeing
                int escape = ACT_START[firstOf(4)];
                float since = (t - escape) / 1000.0F;
                float fade = state == 5 ? 1.0F - (t - ACT_START[firstOf(5)]) / (float) (ACT_TOTAL - ACT_START[firstOf(5)]) : 1.0F;
                burst(g, left + ox + ACT_STAR[c][firstOf(4)][0], top + oy + ACT_STAR[c][firstOf(4)][1], since, (int) ((round + c) % 3), colour);
                star(g, sx, sy, 2, colour, state == 4 ? 4 : (int) ((now / 100L) % 8), fade);
            }
        }
    }

    /** The burst when a star breaks free: a ring of light, a shower of little stars, or a flash of rays. */
    private static void burst(GuiGraphics g, int cx, int cy, float since, int kind, int colour) {
        if (since < 0.0F || since > 0.6F) return;
        float p = since / 0.6F;
        int rgb = STAR_RGB[colour];
        if (since < 0.08F) g.fill(cx - 2, cy - 2, cx + 3, cy + 3, alpha(0.8F) | 0xFFFFFF);   // the flash
        switch (kind) {
            case 0 -> {                                        // a ring spreading out
                float r = 2.0F + p * 12.0F;
                for (int a = 0; a < 28; a++) {
                    double ang = a * Math.PI * 2 / 28;
                    int px = cx + Math.round((float) Math.cos(ang) * r), py = cy + Math.round((float) Math.sin(ang) * r);
                    g.fill(px, py, px + 1, py + 1, alpha(1.0F - p) | rgb);
                }
            }
            case 1 -> {                                        // little stars flying off
                for (int a = 0; a < 9; a++) {
                    double ang = a * Math.PI * 2 / 9 + 0.3;
                    float r = 2.0F + p * (10.0F + a % 3 * 3.0F);
                    star(g, cx + Math.round((float) Math.cos(ang) * r), cy + Math.round((float) Math.sin(ang) * r) + Math.round(p * p * 4.0F),
                            0, (colour + a) % 3, 1 + a % 3, 1.0F - p);
                }
            }
            default -> {                                       // rays shooting out
                for (int a = 0; a < 8; a++) {
                    double ang = a * Math.PI / 4;
                    float r0 = 2.0F + p * 8.0F, r1 = r0 + (a % 2 == 0 ? 6.0F : 3.0F) * (1.0F - p);
                    for (float r = r0; r <= r1; r += 1.0F) {
                        int px = cx + Math.round((float) Math.cos(ang) * r), py = cy + Math.round((float) Math.sin(ang) * r);
                        g.fill(px, py, px + 1, py + 1, alpha(1.0F - p) | rgb);
                    }
                }
            }
        }
    }

    private static int firstOf(int state) {
        for (int i = 0; i < ACT_STATE.length; i++) if (ACT_STATE[i] == state) return i;
        return 0;
    }

    private static int alpha(float a) {
        return (int) (Mth.clamp(a, 0.0F, 1.0F) * 255.0F) << 24;
    }

    private static long hash(long v) {
        v ^= v >>> 33;
        v *= 0xFF51AFD7ED558CCDL;
        v ^= v >>> 33;
        return v & Long.MAX_VALUE;
    }

    /** One star from the sheet: kind (sparkle, four-, eight-pointed), colour (pink, gold, ice), frame. */
    private static void star(GuiGraphics g, int x, int y, int kind, int colour, int frame, float alpha) {
        if (alpha <= 0.02F) return;
        RenderSystem.enableBlend();
        RenderSystem.setShaderColor(1.0F, 1.0F, 1.0F, Math.min(1.0F, alpha));
        g.blit(STARS, x - 5, y - 5, frame * 11, (kind * 3 + colour) * 11, 11, 11, 88, 99);
        RenderSystem.setShaderColor(1.0F, 1.0F, 1.0F, 1.0F);
    }
}
