package com.reya.goldenquarry.client;

import com.mojang.blaze3d.systems.RenderSystem;
import com.reya.goldenquarry.GoldenQuarry;
import net.minecraft.Util;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;

/**
 * The tentacles round the vacuum chest's GUI and the stars they pull in. The tentacles are drawn
 * frame by frame by tools/gen_tentacles.py (glossy back with dark spots, pink underside with round
 * suckers, the tip curled; three colourings, each tentacle its own): one row of 32 frames per
 * tentacle in vacuum_chest_tentacles.png. They sway slowly, the waves running in, and are drawn in
 * and reach out again. Their roots are under the frame, which is drawn over them. Some catch a star
 * when they have reached out, hold it in the curl of the tip while they are drawn in and then let
 * it fly into the chest; more stars drift in round them, twinkling: little sparkles, four- and
 * eight-pointed stars, pink, gold and ice blue.
 */
final class Tentacles {
    private static final ResourceLocation SHEET = new ResourceLocation(GoldenQuarry.MODID, "textures/gui/vacuum_chest_tentacles.png");
    private static final ResourceLocation STARS = new ResourceLocation(GoldenQuarry.MODID, "textures/gui/vacuum_chest_stars.png");
    private static final int SIZE = 96, FRAMES = 32, REACH = 40;
    /** One frame lasts this long: a whole sway, in and out, takes FRAMES of them. */
    private static final long FRAME_MS = 180L;
    /** Root x, y (GUI pixels), direction out, length: as in tools/gen_tentacles.py, in its order. */
    private static final float[][] TENTACLES;

    static {
        float r = 216 - 1;
        TENTACLES = new float[][]{
                {6, 14, -0.75F, -0.66F, 54}, {34, 13, -0.2F, -0.98F, 40}, {4, 48, -0.98F, -0.2F, 40},
                {4, 104, -0.97F, 0.25F, 46}, {9, 152, -0.8F, 0.6F, 52}, {18, 160, -0.4F, 0.92F, 40},
                {r - 6, 14, 0.75F, -0.66F, 54}, {r - 34, 13, 0.2F, -0.98F, 40}, {r - 4, 48, 0.98F, -0.2F, 40},
                {r - 4, 104, 0.97F, 0.25F, 46}, {r - 9, 152, 0.8F, 0.6F, 52}, {r - 18, 160, 0.4F, 0.92F, 40}};
    }

    // <generated by tools/gen_tentacles.py>
    private static final float[] PHASES = {0.0F, 1.7F, 3.1F, 5.0F, 3.6F, 0.4F, 2.3F, 4.2F, 0.9F, 1.2F, 2.8F, 5.6F};
    /** For the tentacles that catch stars: where the star sits, in each frame (sprite pixels). */
    private static final int[][][] GRIPS = {
            {{66, 41}, {64, 40}, {63, 40}, {61, 41}, {60, 42}, {59, 43}, {59, 44}, {59, 45}, {60, 46}, {62, 46}, {64, 46}, {66, 45}, {67, 44}, {68, 42}, {68, 41}, {67, 41}, {66, 41}, {65, 42}, {64, 44}, {63, 46}, {63, 49}, {63, 51}, {64, 53}, {64, 54}, {65, 54}, {66, 54}, {67, 53}, {68, 52}, {69, 50}, {69, 47}, {69, 45}, {68, 43}},
            null,
            null,
            {{68, 50}, {68, 49}, {68, 48}, {69, 48}, {69, 49}, {69, 50}, {70, 52}, {69, 55}, {69, 57}, {68, 60}, {66, 61}, {64, 62}, {62, 62}, {61, 61}, {60, 59}, {60, 57}, {60, 55}, {61, 53}, {62, 52}, {64, 51}, {66, 51}, {67, 51}, {69, 53}, {70, 54}, {70, 56}, {70, 57}, {69, 57}, {68, 57}, {67, 56}, {67, 55}, {67, 53}, {67, 52}},
            null,
            null,
            null,
            {{50, 74}, {51, 74}, {53, 74}, {54, 73}, {55, 72}, {56, 71}, {55, 70}, {55, 69}, {54, 68}, {53, 68}, {51, 67}, {50, 67}, {50, 67}, {50, 68}, {50, 68}, {51, 69}, {53, 70}, {55, 70}, {57, 70}, {59, 69}, {60, 68}, {60, 67}, {60, 65}, {58, 65}, {56, 65}, {54, 66}, {52, 67}, {50, 68}, {49, 69}, {48, 71}, {48, 72}, {49, 73}},
            null,
            null,
            {{51, 27}, {51, 28}, {50, 30}, {48, 31}, {46, 33}, {43, 33}, {41, 33}, {39, 33}, {38, 33}, {37, 32}, {37, 31}, {37, 29}, {38, 28}, {40, 27}, {43, 26}, {45, 26}, {48, 27}, {49, 28}, {50, 30}, {51, 32}, {50, 34}, {49, 35}, {48, 36}, {47, 36}, {46, 36}, {45, 35}, {45, 34}, {45, 31}, {46, 29}, {47, 27}, {49, 26}, {50, 26}},
            null,
    };
    // </generated>

    void draw(GuiGraphics g, int left, int top) {
        long now = Util.getMillis();
        // the stars drifting in round them first, so the tentacles pass over them
        double t = now / 1000.0D;
        for (int k = 0; k < 26; k++) {
            float[] tc = TENTACLES[k % TENTACLES.length];
            double speed = 0.12D + (k * 37 % 10) * 0.012D;
            double p = (t * speed + k * 0.37D) % 1.0D;
            double side = ((k * 7) % 5 - 2) * 5.0D + (k % 3 - 1) * 2.0D;
            double far = tc[4] * (0.8D + (k % 4) * 0.12D);
            double sx = tc[0] + tc[2] * far - tc[3] * side, sy = tc[1] + tc[3] * far + tc[2] * side;
            double ex = tc[0] - tc[2] * 4.0D, ey = tc[1] - tc[3] * 4.0D;
            double e = Math.pow(p, 1.6D);
            int kind = k % 3 == 0 ? 2 : k % 3 == 1 ? 0 : 1;
            star(g, left + (int) Math.round(sx + (ex - sx) * e), top + (int) Math.round(sy + (ey - sy) * e),
                    kind, (k / 3) % 3, (int) ((now / (120L + k % 4 * 30L) + k) % 8), (float) Math.min(1.0D, p / 0.25D));
        }
        for (int i = 0; i < TENTACLES.length; i++) {
            float[] tc = TENTACLES[i];
            long step = now / FRAME_MS + i * 7L;
            int frame = (int) (step % FRAMES);
            int ox = Math.round(tc[0] - (SIZE / 2.0F - REACH * tc[2]));
            int oy = Math.round(tc[1] - (SIZE / 2.0F - REACH * tc[3]));
            g.blit(SHEET, left + ox, top + oy, frame * SIZE, i * SIZE, SIZE, SIZE, SIZE * FRAMES, SIZE * TENTACLES.length);
            if (GRIPS[i] != null) caught(g, left, top, i, ox, oy, (step % FRAMES + (now % FRAME_MS) / (float) FRAME_MS) / FRAMES);
        }
    }

    /**
     * The star a catcher holds: it is caught when the tentacle is furthest out, sits in the curl of
     * its tip while it is drawn in, and at the end flies in to the root and is gone.
     */
    private static void caught(GuiGraphics g, int left, int top, int i, int ox, int oy, float cycle) {
        double a = (2 * Math.PI * cycle + PHASES[i]) % (2 * Math.PI);
        if (a < 0) a += 2 * Math.PI;
        double k = (a - Math.PI / 2) / Math.PI;               // 0 caught .. 1 drawn in
        if (k < 0.0D || k > 1.0D) return;
        int[][] grips = GRIPS[i];
        int f = (int) (cycle * FRAMES) % FRAMES;
        double x = ox + grips[f][0], y = oy + grips[f][1];
        if (k > 0.85D) {                                       // let go: into the chest
            double e = (k - 0.85D) / 0.15D;
            x += (TENTACLES[i][0] - TENTACLES[i][2] * 6.0D - x) * e;
            y += (TENTACLES[i][1] - TENTACLES[i][3] * 6.0D - y) * e;
        }
        int twinkle = k < 0.12D ? (int) (k / 0.12D * 3) : 3 + (int) ((Util.getMillis() / 160L) % 2);
        star(g, left + (int) Math.round(x), top + (int) Math.round(y), 2, i % 2 == 0 ? 1 : 0, twinkle, 1.0F);
    }

    /** One star from the sheet: kind (sparkle, four-, eight-pointed), colour (pink, gold, ice), frame. */
    private static void star(GuiGraphics g, int x, int y, int kind, int colour, int frame, float alpha) {
        if (alpha <= 0.02F) return;
        RenderSystem.enableBlend();
        RenderSystem.setShaderColor(1.0F, 1.0F, 1.0F, alpha);
        g.blit(STARS, x - 5, y - 5, frame * 11, (kind * 3 + colour) * 11, 11, 11, 88, 99);
        RenderSystem.setShaderColor(1.0F, 1.0F, 1.0F, 1.0F);
    }
}
