package com.reya.singularityfusion.gui;

/** Generated by tools/layout.py: where everything is in the fusion core's screen. Edit that file, not this one. */
public final class Layouts {
    public static final int W = 256, H = 256, MH = 160, FRAME = 7, TEX_H = 512;
    public static final int PANEL_X = 40, INV_X = 48, INV_Y = 172, HOTBAR_Y = 230;
    public static final int[] TITLE = {64, 5, 192, 19};
    public static final int[] VIEW = {128, 62};
    public static final int VIEW_R = 36;
    public static final int[][] PYLONS = {{27, 24}, {29, 44}, {30, 64}, {30, 84}, {29, 104}, {27, 124}, {213, 24}, {211, 44}, {210, 64}, {210, 84}, {211, 104}, {213, 124}};
    public static final int[] CATALYST = {98, 108}, START = {119, 107}, OUTPUT = {140, 108};
    public static final int[] ENERGY = {12, 24, 10, 122}, PROGRESS = {234, 24, 10, 122};
    public static final int[] STATUS_Y = {131, 142};
    public static final int[] SHEET_START = {0, 272}, SHEET_PYLON = {80, 272}, SHEET_BAR = {120, 272}, SHEET_MASK = {144, 272};
    public static final int MASK_SIZE = 80;
    public static final int[] SHEET_JEI = {0, 394}, JEI = {168, 118}, JEI_CENTER = {62, 54}, JEI_OUTPUT = {146, 46};
    public static final int JEI_RING_R = 40, JEI_TEXT_Y = 106;

    private Layouts() {
    }
}
