package com.reya.singularityfusion.gui;

/** Generated by tools/layout.py: where everything is in the fusion core's screen and on its textures. Edit that file, not this one. */
public final class Layouts {
    public static final int W = 256, H = 256, MH = 160, FRAME = 8;
    public static final int PANEL_X = 40, INV_X = 48, INV_Y = 172, HOTBAR_Y = 230;
    public static final int[] TITLE = {68, 1, 188, 19}, WINDOW = {8, 8, 248, 152}, HOLE = {128, 64}, INV_WINDOW = {46, 156, 210, 250};
    public static final int[][] PYLONS = {{27, 24}, {29, 44}, {30, 64}, {30, 84}, {29, 104}, {27, 124}, {213, 24}, {211, 44}, {210, 64}, {210, 84}, {211, 104}, {213, 124}};
    public static final int PORTHOLE = 22, ORB = 24;
    public static final int[] CATALYST = {95, 108}, START = {116, 103}, OUTPUT = {145, 108};
    public static final int[] ENERGY = {12, 24, 10, 122}, PROGRESS = {234, 24, 10, 122}, STATUS = {50, 130, 206, 152};
    /** The gems on the frame, round it clockwise from the top left: x, y, radius. */
    public static final float[][] GEMS = {{8.5F, 8.5F, 3.6F}, {40F, 4F, 2F}, {69F, 10F, 2.475F}, {187F, 10F, 2.475F}, {216F, 4F, 2F}, {247.5F, 8.5F, 3.6F}, {252F, 56F, 2.5F}, {252F, 104F, 2.5F}, {247.5F, 151.5F, 3.6F}, {216F, 156F, 2F}, {209F, 249F, 2.25F}, {47F, 249F, 2.25F}, {40F, 156F, 2F}, {8.5F, 151.5F, 3.6F}, {4F, 104F, 2.5F}, {4F, 56F, 2.5F}};
    public static final int FRAME_TEX = 512, SPACE_TEX = 512, WIDGETS_TEX = 512, PLANETS_TEX = 256;
    public static final int[] SPACE_BASE = {0, 0, 480, 288}, SPACE_WISPS = {0, 288, 512, 224};
    public static final int[] W_PORT_STEEL = {0, 0, 44, 44}, W_PORT_VIOLET = {44, 0, 44, 44}, W_PORT_GOLD = {88, 0, 44, 44}, W_PORT_GLOSS = {132, 0, 44, 44}, W_ORB = {176, 0, 48, 48}, W_ORB_RING = {368, 0, 64, 64}, W_BLOOM = {432, 0, 64, 64};
    public static final int[] W_TUBE = {0, 64, 28, 252}, W_PLASMA_VIOLET = {28, 64, 20, 244}, W_PLASMA_GOLD = {48, 64, 20, 244}, W_FLOW = {68, 64, 20, 128}, W_HOLOGRAM = {88, 64, 312, 44}, W_GLOSS = {88, 108, 64, 32}, W_ARROW = {152, 108, 44, 30}, W_SPARKLE = {196, 108, 16, 16}, W_JEI_FRAME = {88, 140, 336, 236};
    public static final int[] P_GIANT = {0, 0, 64, 64}, P_OCEAN = {64, 0, 48, 48}, P_ICE = {112, 0, 48, 48}, P_LAVA = {160, 0, 40, 40}, P_MOON = {200, 0, 24, 24}, P_SHADE = {0, 64, 64, 64}, P_RIM = {64, 64, 64, 64};
    public static final int[] P_RING_BACK = {128, 64, 128, 20}, P_RING_FRONT = {128, 84, 128, 20}, P_GALAXY = {0, 128, 64, 64}, P_GLINT = {64, 128, 32, 32}, P_STREAK = {96, 128, 64, 8}, P_ATMOS = {160, 128, 32, 32}, P_GLOW = {192, 128, 64, 64};
    public static final int[] JEI = {168, 118}, JEI_CENTER = {62, 54}, JEI_OUTPUT = {146, 46}, JEI_ARROW = {117, 47};
    public static final int JEI_RING_R = 40, JEI_TEXT_Y = 106;

    private Layouts() {
    }
}
