"""Where everything is in the fusion core's screen.

    python3 tools/layout.py

The menu (slots), the screen (the viewport, the pylon columns, the bars, the button) and the texture (gen_textures.py)
all read these numbers; this writes them into src/main/java/com/reya/singularityfusion/gui/Layouts.java, and check.py
makes sure the Java file is current and nothing overlaps. Coordinates are GUI pixels from the panel's top left.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
JAVA_OUT = os.path.join(ROOT, "src", "main", "java", "com", "reya", "singularityfusion", "gui", "Layouts.java")

W = 256                     # the panel's width (the texture's too)
FRAME = 7                   # its metal border
MH = 160                    # the machine area's height; the player's inventory panel hangs under it
INV_W = 176
TITLE = (64, 5, 192, 19)    # the title's plaque, riveted over the top of the frame: x1, y1, x2, y2
VIEW = (128, 62)            # the viewport's middle: stars and the singularity in it
VIEW_R = 36                 # its radius (its ring, 4 wide, round it)
PYLONS_LEFT = [(30 - (3 if i in (0, 5) else 1 if i in (1, 4) else 0), 24 + 20 * i) for i in range(6)]   # the pylons' items, a gentle curve
PYLONS_RIGHT = [(W - 30 - 16 + (3 if i in (0, 5) else 1 if i in (1, 4) else 0), 24 + 20 * i) for i in range(6)]
CATALYST = (98, 108)        # the catalyst slot (its item's top left)
START = (119, 107)          # the start button, 18 square, between the catalyst and the output
OUTPUT = (140, 108)
ENERGY = (12, 24, 10, 122)  # the energy bar: x, y, width, height (fills from the bottom)
PROGRESS = (W - 22, 24, 10, 122)
STATUS_Y = (131, 142)       # the status line and the info line under it


def inventory(mh):
    """The player inventory panel under a machine area mh tall: its x, the slots' x and y, the hotbar's y, height."""
    px = (W - INV_W) // 2
    inv_y = mh + 12
    hot_y = inv_y + 58
    return px, px + 8, inv_y, hot_y, hot_y + 18 + 8


PANEL_X, INV_X, INV_Y, HOTBAR_Y, H = inventory(MH)


class Sheet:
    """The widgets under the panel on its texture (fusion_core.png is 256 x 512): each a strip of states."""
    TEX_H = 512
    START = (0, 272)            # 18 square: ready, hovered, can't start, fusing
    PYLON_FRAME = (80, 272)     # 18 square: a pylon's item frame: no pylon there, a pylon
    BAR = (120, 272)            # the bars' fills: energy (10 x 122), progress (10 x 122)
    MASK = (144, 272)           # the viewport's ring and what is round it, its inside clear: drawn over the singularity
    MASK_SIZE = 2 * (VIEW_R + 4)
    JEI = (0, 394)              # JEI's fusion page background (Jei.SIZE), under the bars
    REGIONS = [("start", 0, 272, 72, 18), ("pylon", 80, 272, 36, 18), ("bars", 120, 272, 20, 122),
               ("mask", 144, 272, 2 * (VIEW_R + 4), 2 * (VIEW_R + 4)), ("jei", 0, 394, 168, 118)]


class Jei:
    """JEI's page for a fusion: the ingredients on a ring round the catalyst (in a little viewport with the
    singularity), an arrow to the output, the energy and time along the bottom."""
    SIZE = (168, 118)
    CENTER = (62, 54)           # the catalyst's middle, and the ring's
    RING_R = 40                 # the ingredients' middles sit on this ring
    VIEW_R = 22                 # the little viewport round the catalyst
    ARROW = (118, 47)           # 22 x 15
    OUTPUT = (146, 46)          # the output's item, top left
    TEXT_Y = 106


def java():
    def pts(name, points):
        return "    public static final int[][] %s = {%s};\n" % (name, ", ".join("{%d, %d}" % p for p in points))

    out = ["package com.reya.singularityfusion.gui;\n\n",
           "/** Generated by tools/layout.py: where everything is in the fusion core's screen. Edit that file, not this one. */\n",
           "public final class Layouts {\n",
           "    public static final int W = %d, H = %d, MH = %d, FRAME = %d, TEX_H = %d;\n" % (W, H, MH, FRAME, Sheet.TEX_H),
           "    public static final int PANEL_X = %d, INV_X = %d, INV_Y = %d, HOTBAR_Y = %d;\n" % (PANEL_X, INV_X, INV_Y, HOTBAR_Y),
           "    public static final int[] TITLE = {%d, %d, %d, %d};\n" % TITLE,
           "    public static final int[] VIEW = {%d, %d};\n" % VIEW,
           "    public static final int VIEW_R = %d;\n" % VIEW_R,
           pts("PYLONS", PYLONS_LEFT + PYLONS_RIGHT),
           "    public static final int[] CATALYST = {%d, %d}, START = {%d, %d}, OUTPUT = {%d, %d};\n" % (CATALYST + START + OUTPUT),
           "    public static final int[] ENERGY = {%d, %d, %d, %d}, PROGRESS = {%d, %d, %d, %d};\n" % (ENERGY + PROGRESS),
           "    public static final int[] STATUS_Y = {%d, %d};\n" % STATUS_Y,
           "    public static final int[] SHEET_START = {%d, %d}, SHEET_PYLON = {%d, %d}, SHEET_BAR = {%d, %d}, SHEET_MASK = {%d, %d};\n"
           % (Sheet.START + Sheet.PYLON_FRAME + Sheet.BAR + Sheet.MASK),
           "    public static final int MASK_SIZE = %d;\n" % Sheet.MASK_SIZE,
           "    public static final int[] SHEET_JEI = {%d, %d}, JEI = {%d, %d}, JEI_CENTER = {%d, %d}, JEI_OUTPUT = {%d, %d};\n"
           % (Sheet.JEI + Jei.SIZE + Jei.CENTER + Jei.OUTPUT),
           "    public static final int JEI_RING_R = %d, JEI_TEXT_Y = %d;\n" % (Jei.RING_R, Jei.TEXT_Y),
           "\n    private Layouts() {\n    }\n}\n"]
    return "".join(out)


def main():
    os.makedirs(os.path.dirname(JAVA_OUT), exist_ok=True)
    with open(JAVA_OUT, "w", encoding="utf-8") as f:
        f.write(java())
    print("wrote " + os.path.relpath(JAVA_OUT, ROOT))


if __name__ == "__main__":
    main()
