package com.reya.boundlessrouters.gui;

/** Generated by tools/layout.py: where everything is in the GUIs. Edit that file, not this one. */
public final class Layouts {
    public static final int W = 232, FRAME = 6;
    public static final int[] HEADER = {6, 6, 226, 21};

    public static final class Router {
        public static final int MH = 124, H = 220, PANEL_X = 28, INV_X = 36, INV_Y = 136, HOTBAR_Y = 194;
        public static final int[] BUFFER = {108, 36}, CORE = {116, 44}, REDSTONE = {10, 26};
        public static final int CORE_R = 19, GEAR = 8, BUS_Y = 79, LED = 4, GAUGE_R = 9;
        public static final int[] GAUGE = {164, 31};
        public static final int[][] MODULES = {{24, 86}, {42, 86}, {60, 86}, {78, 86}, {96, 86}, {114, 86}, {132, 86}, {150, 86}, {168, 86}};
        public static final int[][] GEARS = {{29, 106}, {47, 106}, {65, 106}, {83, 106}, {101, 106}, {119, 106}, {137, 106}, {155, 106}, {173, 106}};
        public static final int[][] UPGRADES = {{206, 24}, {206, 42}, {206, 60}, {206, 78}, {206, 96}};
        public static final int[][] INFO = {{10, 46}, {10, 56}, {10, 66}};
        public static final int[][] LEDS = {{156, 52}, {162, 52}, {168, 52}, {156, 58}, {162, 58}, {168, 58}, {156, 64}, {162, 64}, {168, 64}};

        private Router() {
        }
    }

    public static final class Module {
        public static final int MH = 136, H = 232, PANEL_X = 28, INV_X = 36, INV_Y = 148, HOTBAR_Y = 206;
        public static final int[] BACK = {9, 7}, DIR_LABEL = {39, 83}, ICON = {24, 6};
        public static final int[] PANEL = {10, 98, 222, 128}, INFO = {142, 62, 222, 88};
        public static final int DIR_CELL = 16, TOGGLE = 14;
        /** The direction picker's buttons, in RelativeDirection's order: none, front, back, up, down, left, right. */
        public static final int[][] DIRS = {{48, 62}, {30, 44}, {48, 26}, {30, 26}, {30, 62}, {12, 44}, {48, 44}};
        public static final int[][] FILTER = {{78, 28}, {96, 28}, {114, 28}, {78, 46}, {96, 46}, {114, 46}, {78, 64}, {96, 64}, {114, 64}};
        public static final int[][] TOGGLES = {{142, 28}, {158, 28}, {174, 28}, {190, 28}, {142, 44}, {158, 44}, {174, 44}, {190, 44}};

        private Module() {
        }
    }

    /** Where the widget sheet's pieces are (widgets.png). */
    public static final class Sheet {
        public static final int W = 128, H = 128;
        public static final int[] BUTTON = {0, 0};
        public static final int[] TOGGLE = {64, 0};
        public static final int[] GEAR = {0, 16};
        public static final int[] BACK = {24, 16};
        public static final int[] SMALL = {48, 16};
        public static final int[] REDSTONE = {0, 30};
        public static final int[] INFO = {60, 30};
        public static final int[] DIRS = {0, 44};
        public static final int[] OPTS = {0, 56};
        public static final int[] MISC = {0, 68};

        private Sheet() {
        }
    }

    private Layouts() {
    }
}
