"""Writes the mod's three languages from one table, so none of them misses a key.

    python3 tools/gen_lang.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LANG = os.path.join(ROOT, "src", "main", "resources", "assets", "boundlessrouters", "lang")

P = "boundlessrouters"

# key: (English, Ukrainian, Russian)
T = {
    "itemGroup.%s" % P: ("Boundless Routers", "Безмежні маршрутизатори", "Безграничные маршрутизаторы"),
    "block.%s.router" % P: ("Item Router", "Маршрутизатор предметів", "Маршрутизатор предметов"),
    "item.%s.blank_module" % P: ("Blank Module", "Порожній модуль", "Пустой модуль"),
    "item.%s.blank_upgrade" % P: ("Blank Upgrade", "Порожнє покращення", "Пустое улучшение"),

    # ------------------------------------------------------------------ modules
    "item.%s.sender_module" % P: ("Sender Module", "Модуль-відправник", "Модуль-отправитель"),
    "item.%s.sender_module.desc" % P: (
        "Sends items from the buffer to the first inventory in its direction, or to the one it is bound to: any distance, any dimension.",
        "Відправляє предмети з буфера в перший інвентар у своєму напрямку або в прив'язаний — на будь-яку відстань, у будь-який вимір.",
        "Отправляет предметы из буфера в первый инвентарь в своём направлении или в привязанный — на любое расстояние, в любое измерение."),
    "item.%s.puller_module" % P: ("Puller Module", "Модуль-витягувач", "Модуль-вытягиватель"),
    "item.%s.puller_module.desc" % P: (
        "Pulls items into the buffer from the inventory next to it in its direction, or from the one it is bound to, anywhere.",
        "Витягує предмети в буфер із сусіднього інвентаря у своєму напрямку або з прив'язаного — будь-де.",
        "Вытягивает предметы в буфер из соседнего инвентаря в своём направлении или из привязанного — где угодно."),
    "item.%s.distributor_module" % P: ("Distributor Module", "Модуль-розподільник", "Модуль-распределитель"),
    "item.%s.distributor_module.desc" % P: (
        "Sends items from the buffer to many bound inventories: in turn, at random, nearest or farthest first.",
        "Розсилає предмети з буфера в багато прив'язаних інвентарів: по черзі, навмання, спершу ближчі чи дальші.",
        "Рассылает предметы из буфера во множество привязанных инвентарей: по очереди, случайно, сначала ближние или дальние."),
    "item.%s.dropper_module" % P: ("Dropper Module", "Модуль-скидач", "Модуль-выбрасыватель"),
    "item.%s.dropper_module.desc" % P: ("Drops items from the buffer into the world in its direction.",
                                        "Викидає предмети з буфера у світ у своєму напрямку.",
                                        "Выбрасывает предметы из буфера в мир в своём направлении."),
    "item.%s.flinger_module" % P: ("Flinger Module", "Модуль-метальник", "Модуль-метатель"),
    "item.%s.flinger_module.desc" % P: ("Throws items from the buffer as fast and as high as you set it.",
                                        "Кидає предмети з буфера так швидко й так високо, як налаштуєш.",
                                        "Бросает предметы из буфера так быстро и так высоко, как настроишь."),
    "item.%s.placer_module" % P: ("Placer Module", "Модуль-будівельник", "Модуль-строитель"),
    "item.%s.placer_module.desc" % P: ("Places blocks from the buffer in its direction.",
                                       "Ставить блоки з буфера у своєму напрямку.",
                                       "Ставит блоки из буфера в своём направлении."),
    "item.%s.breaker_module" % P: ("Breaker Module", "Модуль-руйнівник", "Модуль-разрушитель"),
    "item.%s.breaker_module.desc" % P: (
        "Breaks the block in its direction into the buffer, as a netherite pickaxe would, with silk touch or any fortune you set.",
        "Ламає блок у своєму напрямку в буфер, як незеритова кирка, з шовковим дотиком чи будь-якою удачею.",
        "Ломает блок в своём направлении в буфер, как незеритовая кирка, с шёлковым касанием или любой удачей."),
    "item.%s.vacuum_module" % P: ("Vacuum Module", "Модуль-пилосос", "Модуль-пылесос"),
    "item.%s.vacuum_module.desc" % P: ("Picks dropped items up into the buffer round the router, or round a spot in its direction.",
                                       "Збирає в буфер предмети, що лежать навколо маршрутизатора або навколо точки в його напрямку.",
                                       "Собирает в буфер предметы, лежащие вокруг маршрутизатора или вокруг точки в его направлении."),
    "item.%s.void_module" % P: ("Void Module", "Модуль-знищувач", "Модуль-уничтожитель"),
    "item.%s.void_module.desc" % P: ("Destroys items in the buffer that pass its filter.",
                                     "Знищує предмети в буфері, які пропускає його фільтр.",
                                     "Уничтожает предметы в буфере, которые пропускает его фильтр."),
    "item.%s.player_module" % P: ("Player Module", "Модуль гравця", "Модуль игрока"),
    "item.%s.player_module.desc" % P: (
        "Moves items between the buffer and its bound player's inventory, armour, offhand or ender chest, wherever they are.",
        "Переносить предмети між буфером та інвентарем, бронею, другою рукою чи скринею Енду прив'язаного гравця, де б він не був.",
        "Переносит предметы между буфером и инвентарём, бронёй, второй рукой или сундуком Края привязанного игрока, где бы он ни был."),
    "item.%s.detector_module" % P: ("Detector Module", "Модуль-детектор", "Модуль-детектор"),
    "item.%s.detector_module.desc" % P: ("Gives out a redstone signal in its direction while the buffer holds what it looks for.",
                                         "Подає редстоун-сигнал у своєму напрямку, поки в буфері є те, що він шукає.",
                                         "Подаёт редстоун-сигнал в своём направлении, пока в буфере есть то, что он ищет."),
    "item.%s.extruder_module" % P: ("Extruder Module", "Модуль-висувач", "Модуль-выдвигатель"),
    "item.%s.extruder_module.desc" % P: (
        "With a redstone signal builds a line of blocks from the buffer in its direction; without one takes it back.",
        "Із редстоун-сигналом висуває лінію блоків із буфера у своєму напрямку, без сигналу — забирає її назад.",
        "С редстоун-сигналом выдвигает линию блоков из буфера в своём направлении, без сигнала — забирает её обратно."),

    # ------------------------------------------------------------------ upgrades
    "item.%s.speed_upgrade" % P: ("Speed Upgrade", "Покращення швидкості", "Улучшение скорости"),
    "item.%s.speed_upgrade.desc" % P: ("Each takes two ticks off the time between the router's runs, down to every tick.",
                                       "Кожне скорочує час між запусками маршрутизатора на два тіки, аж до кожного тіку.",
                                       "Каждое сокращает время между запусками маршрутизатора на два тика, вплоть до каждого тика."),
    "item.%s.stack_upgrade" % P: ("Stack Upgrade", "Покращення стосу", "Улучшение стака"),
    "item.%s.stack_upgrade.desc" % P: ("Each doubles the items a module moves a run, up to a full stack.",
                                       "Кожне подвоює кількість предметів, яку модуль переносить за раз, аж до цілого стосу.",
                                       "Каждое удваивает количество предметов, которое модуль переносит за раз, вплоть до целого стака."),
    "item.%s.range_upgrade" % P: ("Range Upgrade", "Покращення дальності", "Улучшение дальности"),
    "item.%s.range_upgrade.desc" % P: ("Each adds four blocks to how far senders look and extruders reach. No limit.",
                                       "Кожне додає чотири блоки до того, як далеко шукають відправники й сягають висувачі. Без меж.",
                                       "Каждое добавляет четыре блока к тому, как далеко ищут отправители и достают выдвигатели. Без предела."),
    "item.%s.muffler_upgrade" % P: ("Muffler Upgrade", "Покращення-глушник", "Улучшение-глушитель"),
    "item.%s.muffler_upgrade.desc" % P: ("Silences the router: no sounds, no particles.",
                                         "Робить маршрутизатор тихим: без звуків і часточок.",
                                         "Делает маршрутизатор тихим: без звуков и частиц."),

    # ------------------------------------------------------------------ tooltips and messages
    "tooltip.%s.router" % P: ("Plug modules into it to move items about. Keeps its modules when broken.",
                              "Встав модулі, щоб переносити предмети. Зберігає модулі, коли його зламати.",
                              "Вставь модули, чтобы переносить предметы. Сохраняет модули, если его сломать."),
    "tooltip.%s.router.holds" % P: ("Holds %s modules and %s upgrades", "Містить модулів: %s, покращень: %s",
                                    "Содержит модулей: %s, улучшений: %s"),
    "tooltip.%s.direction" % P: ("Direction: %s", "Напрямок: %s", "Направление: %s"),
    "tooltip.%s.target" % P: ("Bound to %s (%s)", "Прив'язаний до %s (%s)", "Привязан к %s (%s)"),
    "tooltip.%s.targets" % P: ("Targets: %s", "Цілей: %s", "Целей: %s"),
    "tooltip.%s.no_player" % P: ("No player bound", "Гравця не прив'язано", "Игрок не привязан"),
    "tooltip.%s.player" % P: ("Player: %s", "Гравець: %s", "Игрок: %s"),
    "tooltip.%s.blacklist" % P: ("Filter: all but %s listed", "Фільтр: усе, крім %s з переліку", "Фильтр: всё, кроме %s из списка"),
    "tooltip.%s.whitelist" % P: ("Filter: only %s listed", "Фільтр: лише %s з переліку", "Фильтр: только %s из списка"),
    "tooltip.%s.bind_hint.place" % P: ("Sneak + use on an inventory to bind; in the air to unbind",
                                       "Присядь і клацни по інвентарю, щоб прив'язати; у повітря — щоб відв'язати",
                                       "Присядь и кликни по инвентарю, чтобы привязать; в воздух — чтобы отвязать"),
    "tooltip.%s.bind_hint.places" % P: ("Sneak + use on inventories to add or remove them; in the air to clear",
                                        "Присядь і клацай по інвентарях, щоб додати чи прибрати їх; у повітря — очистити",
                                        "Присядь и кликай по инвентарям, чтобы добавить или убрать их; в воздух — очистить"),
    "tooltip.%s.bind_hint.player" % P: ("Sneak + use in the air to bind yourself", "Присядь і клацни в повітря, щоб прив'язати себе",
                                        "Присядь и кликни в воздух, чтобы привязать себя"),
    "tooltip.%s.settings_hint" % P: ("Use: settings. In a router: the gear or a middle click",
                                     "Використай: налаштування. У маршрутизаторі — шестерня чи клік коліщатком",
                                     "Используй: настройки. В маршрутизаторе — шестерёнка или клик колёсиком"),
    "message.%s.bound" % P: ("Bound to %s, %s side (%s)", "Прив'язано до %s, бік: %s (%s)", "Привязано к %s, сторона: %s (%s)"),
    "message.%s.unbound" % P: ("Unbound from %s, %s side (%s)", "Відв'язано від %s, бік: %s (%s)", "Отвязано от %s, сторона: %s (%s)"),
    "message.%s.player_bound" % P: ("Bound to %s", "Прив'язано до %s", "Привязано к %s"),
    "message.%s.cleared" % P: ("Targets cleared", "Цілі очищено", "Цели очищены"),

    # ------------------------------------------------------------------ directions
    "direction.%s.none" % P: ("None", "Немає", "Нет"),
    "direction.%s.front" % P: ("Front", "Спереду", "Спереди"),
    "direction.%s.back" % P: ("Back", "Ззаду", "Сзади"),
    "direction.%s.up" % P: ("Up", "Вгору", "Вверх"),
    "direction.%s.down" % P: ("Down", "Вниз", "Вниз"),
    "direction.%s.left" % P: ("Left", "Ліворуч", "Слева"),
    "direction.%s.right" % P: ("Right", "Праворуч", "Справа"),
    "direction.%s.north" % P: ("north", "північ", "север"),
    "direction.%s.south" % P: ("south", "південь", "юг"),
    "direction.%s.east" % P: ("east", "схід", "восток"),
    "direction.%s.west" % P: ("west", "захід", "запад"),
    "gui.%s.dir.none" % P: ("No direction: round the router itself", "Без напрямку: навколо самого маршрутизатора",
                            "Без направления: вокруг самого маршрутизатора"),
    "gui.%s.dir.front" % P: ("The side the router faces you with", "Бік, яким маршрутизатор повернутий до тебе",
                             "Сторона, которой маршрутизатор повёрнут к тебе"),
    "gui.%s.dir.back" % P: ("The side opposite its front", "Бік навпроти лицьового", "Сторона напротив лицевой"),
    "gui.%s.dir.up" % P: ("Above the router", "Над маршрутизатором", "Над маршрутизатором"),
    "gui.%s.dir.down" % P: ("Below the router", "Під маршрутизатором", "Под маршрутизатором"),
    "gui.%s.dir.left" % P: ("Left, facing its front", "Ліворуч, якщо дивитися на лицьовий бік", "Слева, если смотреть на лицевую сторону"),
    "gui.%s.dir.right" % P: ("Right, facing its front", "Праворуч, якщо дивитися на лицьовий бік", "Справа, если смотреть на лицевую сторону"),
    "gui.%s.no_direction" % P: ("—", "—", "—"),

    # ------------------------------------------------------------------ the router's screen
    "gui.%s.redstone.always" % P: ("Always", "Завжди", "Всегда"),
    "gui.%s.redstone.high" % P: ("Signal", "Сигнал", "Сигнал"),
    "gui.%s.redstone.low" % P: ("No signal", "Без сигналу", "Без сигнала"),
    "gui.%s.redstone.never" % P: ("Never", "Ніколи", "Никогда"),
    "gui.%s.redstone.pulse" % P: ("Pulse", "Імпульс", "Импульс"),
    "gui.%s.redstone.always.tip" % P: ("Runs whatever redstone does", "Працює незалежно від редстоуну", "Работает независимо от редстоуна"),
    "gui.%s.redstone.high.tip" % P: ("Runs only with a redstone signal", "Працює лише з редстоун-сигналом", "Работает только с редстоун-сигналом"),
    "gui.%s.redstone.low.tip" % P: ("Runs only without a redstone signal", "Працює лише без редстоун-сигналу",
                                    "Работает только без редстоун-сигнала"),
    "gui.%s.redstone.never.tip" % P: ("Doesn't run", "Не працює", "Не работает"),
    "gui.%s.redstone.pulse.tip" % P: ("Runs once each time a signal comes on", "Спрацьовує раз щоразу, коли вмикається сигнал",
                                      "Срабатывает раз каждый раз, когда включается сигнал"),
    "gui.%s.redstone.click" % P: ("Click: next · Right click: back", "Клік: далі · ПКМ: назад", "Клик: дальше · ПКМ: назад"),
    "gui.%s.every_tick" % P: ("every tick", "кожен тік", "каждый тик"),
    "gui.%s.interval" % P: ("%s ticks", "%s тіків", "%s тиков"),
    "gui.%s.items" % P: ("%s a run", "%s за раз", "%s за раз"),
    "gui.%s.range" % P: ("%s blocks", "%s блоків", "%s блоков"),
    "gui.%s.info.interval" % P: ("Time between runs", "Час між запусками", "Время между запусками"),
    "gui.%s.info.interval.tip" % P: ("Speed upgrades: %s", "Покращень швидкості: %s", "Улучшений скорости: %s"),
    "gui.%s.info.items" % P: ("Items each module moves a run", "Предметів, які модуль переносить за раз",
                              "Предметов, которые модуль переносит за раз"),
    "gui.%s.info.items.tip" % P: ("Stack upgrades: %s", "Покращень стосу: %s", "Улучшений стака: %s"),
    "gui.%s.info.range" % P: ("How far senders look and extruders reach", "Як далеко шукають відправники й сягають висувачі",
                              "Как далеко ищут отправители и достают выдвигатели"),
    "gui.%s.info.range.tip" % P: ("Range upgrades: %s", "Покращень дальності: %s", "Улучшений дальности: %s"),
    "gui.%s.settings" % P: ("Module settings", "Налаштування модуля", "Настройки модуля"),
    "gui.%s.slot.buffer" % P: ("Buffer", "Буфер", "Буфер"),
    "gui.%s.slot.buffer.tip" % P: ("Every item the router moves passes through here", "Кожен предмет, який переносить маршрутизатор, проходить тут",
                                   "Каждый предмет, который переносит маршрутизатор, проходит здесь"),
    "gui.%s.slot.module" % P: ("Module slot", "Слот модуля", "Слот модуля"),
    "gui.%s.slot.module.tip" % P: ("Modules run left to right; the gear under one opens its settings",
                                   "Модулі працюють зліва направо; шестерня під модулем відкриває його налаштування",
                                   "Модули работают слева направо; шестерёнка под модулем открывает его настройки"),
    "gui.%s.slot.upgrade" % P: ("Upgrade slot", "Слот покращення", "Слот улучшения"),
    "gui.%s.slot.upgrade.tip" % P: ("Speed, stack, range, muffler: as many as fit", "Швидкість, стос, дальність, глушник — скільки влізе",
                                    "Скорость, стак, дальность, глушитель — сколько влезет"),

    # ------------------------------------------------------------------ a module's screen
    "gui.%s.back" % P: ("Back to the router", "Назад до маршрутизатора", "Назад к маршрутизатору"),
    "gui.%s.filter" % P: ("Filter", "Фільтр", "Фильтр"),
    "gui.%s.filter.tip" % P: ("Click with an item to list it, empty-handed to clear; shift-click items in your inventory",
                              "Клацни предметом, щоб додати; порожньою рукою — прибрати; або shift-клік у своєму інвентарі",
                              "Кликни предметом, чтобы добавить; пустой рукой — убрать; или shift-клик в своём инвентаре"),
    "gui.%s.opt.list" % P: ("List mode", "Режим переліку", "Режим списка"),
    "gui.%s.opt.list.white" % P: ("Whitelist: only what is listed", "Білий список: лише те, що в переліку",
                                  "Белый список: только то, что в списке"),
    "gui.%s.opt.list.black" % P: ("Blacklist: everything but what is listed", "Чорний список: усе, крім того, що в переліку",
                                  "Чёрный список: всё, кроме того, что в списке"),
    "gui.%s.opt.list.tip" % P: ("An empty blacklist lets everything through", "Порожній чорний список пропускає все",
                                "Пустой чёрный список пропускает всё"),
    "gui.%s.opt.damage" % P: ("Match damage", "Враховувати пошкодження", "Учитывать повреждение"),
    "gui.%s.opt.nbt" % P: ("Match NBT", "Враховувати NBT", "Учитывать NBT"),
    "gui.%s.opt.tags" % P: ("Match tags", "Враховувати теги", "Учитывать теги"),
    "gui.%s.opt.mod" % P: ("Match mod", "За модом", "По моду"),
    "gui.%s.opt.terminate" % P: ("Terminate", "Зупинка", "Остановка"),
    "gui.%s.opt.redstone" % P: ("Module redstone", "Редстоун модуля", "Редстоун модуля"),
    "gui.%s.opt.silk" % P: ("Silk touch", "Шовковий дотик", "Шёлковое касание"),
    "gui.%s.opt.strong" % P: ("Strong signal", "Сильний сигнал", "Сильный сигнал"),
    "gui.%s.opt.damage.on" % P: ("On", "Увімкнено", "Включено"),
    "gui.%s.opt.damage.off" % P: ("Off", "Вимкнено", "Выключено"),
    "gui.%s.opt.nbt.on" % P: ("On", "Увімкнено", "Включено"),
    "gui.%s.opt.nbt.off" % P: ("Off", "Вимкнено", "Выключено"),
    "gui.%s.opt.tags.on" % P: ("On", "Увімкнено", "Включено"),
    "gui.%s.opt.tags.off" % P: ("Off", "Вимкнено", "Выключено"),
    "gui.%s.opt.mod.on" % P: ("On", "Увімкнено", "Включено"),
    "gui.%s.opt.mod.off" % P: ("Off", "Вимкнено", "Выключено"),
    "gui.%s.opt.terminate.on" % P: ("On", "Увімкнено", "Включено"),
    "gui.%s.opt.terminate.off" % P: ("Off", "Вимкнено", "Выключено"),
    "gui.%s.opt.silk.on" % P: ("On", "Увімкнено", "Включено"),
    "gui.%s.opt.silk.off" % P: ("Off", "Вимкнено", "Выключено"),
    "gui.%s.opt.strong.on" % P: ("Strong: powers through the block next to the router", "Сильний: живить крізь сусідній блок",
                                 "Сильный: питает через соседний блок"),
    "gui.%s.opt.strong.off" % P: ("Weak: only what touches the router", "Слабкий: лише те, що торкається маршрутизатора",
                                  "Слабый: только то, что касается маршрутизатора"),
    "gui.%s.opt.damage.tip" % P: ("Listed items match only at the same damage", "Предмети збігаються лише за однакового пошкодження",
                                  "Предметы совпадают только при одинаковом повреждении"),
    "gui.%s.opt.nbt.tip" % P: ("Listed items match only with the same NBT (enchantments, names...)",
                               "Предмети збігаються лише з однаковим NBT (чари, назви...)",
                               "Предметы совпадают только с одинаковым NBT (чары, названия...)"),
    "gui.%s.opt.tags.tip" % P: ("Items match if they share any item tag with a listed one", "Предмети збігаються, якщо мають спільний тег із переліку",
                                "Предметы совпадают, если имеют общий тег из списка"),
    "gui.%s.opt.mod.tip" % P: ("Items match if they come from the same mod as a listed one",
                               "Предмети збігаються, якщо вони з того самого мода, що й у переліку",
                               "Предметы совпадают, если они из того же мода, что и в списке"),
    "gui.%s.opt.terminate.tip" % P: ("Once it does something, the modules after it don't run this time",
                                     "Коли він щось зробив, наступні модулі цього разу не працюють",
                                     "Когда он что-то сделал, следующие модули в этот раз не работают"),
    "gui.%s.opt.redstone.always" % P: ("Works always", "Працює завжди", "Работает всегда"),
    "gui.%s.opt.redstone.high" % P: ("Works only with a signal", "Працює лише із сигналом", "Работает только с сигналом"),
    "gui.%s.opt.redstone.low" % P: ("Works only without a signal", "Працює лише без сигналу", "Работает только без сигнала"),
    "gui.%s.opt.redstone.tip" % P: ("Besides the router's own redstone mode", "Окрім власного режиму маршрутизатора",
                                    "Помимо собственного режима маршрутизатора"),
    "gui.%s.opt.silk.tip" % P: ("Blocks come off whole", "Блоки знімаються цілими", "Блоки снимаются целыми"),
    "gui.%s.opt.strong.tip" % P: ("Strong signals can loop back into the router", "Сильний сигнал може повернутися в маршрутизатор",
                                  "Сильный сигнал может вернуться в маршрутизатор"),
    "gui.%s.no_target" % P: ("Not bound", "Не прив'язаний", "Не привязан"),
    "gui.%s.unbound.sender" % P: ("Unbound: the first inventory ahead", "Без прив'язки: перший інвентар попереду",
                                  "Без привязки: первый инвентарь впереди"),
    "gui.%s.unbound.puller" % P: ("Unbound: the inventory next to it", "Без прив'язки: сусідній інвентар", "Без привязки: соседний инвентарь"),
    "gui.%s.bound_anywhere" % P: ("Works at any distance, in any dimension", "Працює на будь-якій відстані, у будь-якому вимірі",
                                  "Работает на любом расстоянии, в любом измерении"),
    "gui.%s.target_at" % P: ("%s, %s side · %s", "%s, бік: %s · %s", "%s, сторона: %s · %s"),
    "gui.%s.clear_target" % P: ("Unbind", "Відв'язати", "Отвязать"),
    "gui.%s.clear_targets" % P: ("Clear all targets", "Очистити всі цілі", "Очистить все цели"),
    "gui.%s.no_targets" % P: ("Sneak + use on inventories to add them", "Присядь і клацай по інвентарях, щоб додати",
                              "Присядь и кликай по инвентарям, чтобы добавить"),
    "gui.%s.targets" % P: ("%s targets", "цілей: %s", "целей: %s"),
    "gui.%s.strategy" % P: ("Order", "Порядок", "Порядок"),
    "gui.%s.strategy.tip" % P: ("Which target gets items first", "Яка ціль отримує предмети першою", "Какая цель получает предметы первой"),
    "gui.%s.strategy.round_robin" % P: ("In turn", "По черзі", "По очереди"),
    "gui.%s.strategy.random" % P: ("At random", "Навмання", "Случайно"),
    "gui.%s.strategy.nearest" % P: ("Nearest first", "Спершу ближчі", "Сначала ближние"),
    "gui.%s.strategy.farthest" % P: ("Farthest first", "Спершу дальші", "Сначала дальние"),
    "gui.%s.num.speed" % P: ("Speed", "Швидкість", "Скорость"),
    "gui.%s.num.speed.tip" % P: ("Blocks a tick", "Блоків за тік", "Блоков за тик"),
    "gui.%s.num.pitch" % P: ("Pitch", "Кут", "Угол"),
    "gui.%s.num.pitch.tip" % P: ("Up from its direction, in degrees", "Вгору від напрямку, у градусах", "Вверх от направления, в градусах"),
    "gui.%s.num.yaw" % P: ("Yaw", "Поворот", "Поворот"),
    "gui.%s.num.yaw.tip" % P: ("Aside from its direction, in degrees", "Убік від напрямку, у градусах", "В сторону от направления, в градусах"),
    "gui.%s.num.fortune" % P: ("Fortune", "Удача", "Удача"),
    "gui.%s.num.fortune.tip" % P: ("Up to 10; silk touch turns it off", "До 10; шовковий дотик її вимикає", "До 10; шёлковое касание её выключает"),
    "gui.%s.num.radius" % P: ("Radius", "Радіус", "Радиус"),
    "gui.%s.num.radius.tip" % P: ("Blocks round the spot it vacuums", "Блоків навколо точки, яку він чистить",
                                  "Блоков вокруг точки, которую он чистит"),
    "gui.%s.num.power" % P: ("Power", "Сила", "Сила"),
    "gui.%s.num.power.tip" % P: ("The signal's strength, 1 to 15", "Сила сигналу, від 1 до 15", "Сила сигнала, от 1 до 15"),
    "gui.%s.shift_steps" % P: ("Shift: steps of 10", "Shift: крок 10", "Shift: шаг 10"),
    "gui.%s.breaker_hint" % P: ("Drops go to the buffer", "Здобич іде в буфер", "Добыча идёт в буфер"),
    "gui.%s.vacuum_hint" % P: ("Up to %s; a direction moves the spot", "До %s; напрямок зсуває точку", "До %s; направление сдвигает точку"),
    "gui.%s.no_player" % P: ("Sneak + use in the air to bind", "Присядь і клацни в повітря", "Присядь и кликни в воздух"),
    "gui.%s.clear_player" % P: ("Unbind the player", "Відв'язати гравця", "Отвязать игрока"),
    "gui.%s.section" % P: ("Inventory part", "Частина інвентаря", "Часть инвентаря"),
    "gui.%s.section.tip" % P: ("Where in the player's things it works", "Де серед речей гравця він працює",
                               "Где среди вещей игрока он работает"),
    "gui.%s.section.main" % P: ("Inventory", "Інвентар", "Инвентарь"),
    "gui.%s.section.armor" % P: ("Armour", "Броня", "Броня"),
    "gui.%s.section.offhand" % P: ("Offhand", "Друга рука", "Вторая рука"),
    "gui.%s.section.ender" % P: ("Ender chest", "Скриня Енду", "Сундук Края"),
    "gui.%s.operation" % P: ("Direction of moving", "Напрям перенесення", "Направление переноса"),
    "gui.%s.operation.tip" % P: ("Out of the player, or into them", "З гравця чи до нього", "Из игрока или к нему"),
    "gui.%s.operation.extract" % P: ("Take from player", "Брати в гравця", "Брать у игрока"),
    "gui.%s.operation.insert" % P: ("Give to player", "Давати гравцю", "Давать игроку"),
    "gui.%s.detector_hint" % P: ("While the buffer holds a match", "Поки в буфері є збіг", "Пока в буфере есть совпадение"),
    "gui.%s.extended" % P: ("Put out: %s blocks", "Висунуто: %s блоків", "Выдвинуто: %s блоков"),
    "gui.%s.extruder_hint" % P: ("Signal: build out · none: take back", "Сигнал: висуває · без: забирає",
                                 "Сигнал: выдвигает · без: забирает"),
    "gui.%s.sum.all" % P: ("All items", "Усі предмети", "Все предметы"),
    "gui.%s.sum.none" % P: ("Nothing (empty list)", "Нічого (порожньо)", "Ничего (пусто)"),
    "gui.%s.sum.but" % P: ("All but %s listed", "Усе, крім %s", "Всё, кроме %s"),
    "gui.%s.sum.only" % P: ("Only %s listed", "Лише %s з переліку", "Только %s из списка"),
    "gui.%s.sum.match" % P: ("By: ", "За: ", "По: "),
    "gui.%s.sum.match.item" % P: ("item", "предметом", "предмету"),
    "gui.%s.sum.match.mod" % P: ("mod", "модом", "моду"),
    "gui.%s.sum.match.tags" % P: ("tags", "тегами", "тегам"),
    "gui.%s.sum.match.damage" % P: ("damage", "пошкодженням", "повреждению"),
    "gui.%s.sum.match.nbt" % P: ("NBT", "NBT", "NBT"),
    "gui.%s.sum.redstone.always" % P: ("Redstone: any", "Редстоун: будь-який", "Редстоун: любой"),
    "gui.%s.sum.redstone.high" % P: ("Redstone: on", "Редстоун: є", "Редстоун: есть"),
    "gui.%s.sum.redstone.low" % P: ("Redstone: off", "Редстоун: немає", "Редстоун: нет"),
    "gui.%s.sum.terminate" % P: ("Then: stop", "Потім: стоп", "Затем: стоп"),
}


def main():
    os.makedirs(LANG, exist_ok=True)
    for i, code in enumerate(("en_us", "uk_ua", "ru_ru")):
        data = {k: v[i] for k, v in T.items()}
        with open(os.path.join(LANG, code + ".json"), "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
    print("%d keys in three languages" % len(T))


if __name__ == "__main__":
    main()
