package com.reya.quantumsolar;

/**
 * Every solar panel and quantum generator, in tier order (built by tools/build.py from
 * reference/panels.jpg, which also draws their textures): id, whether it is a quantum generator,
 * its tier among its kind, what it makes (FE a tick) and its colour (for its GUI).
 */
public final class Panels {
    public record Panel(String id, boolean quantum, int tier, int generation, int colour) {
        /** What it holds: a hundred seconds of making for the panels, ten for the generators (the biggest would not fit otherwise). */
        public int capacity() {
            long c = (long) generation * (quantum ? 200L : 2000L);
            return (int) Math.min(Integer.MAX_VALUE, c);
        }

        /** How much it pushes out a tick, into all its neighbours together. */
        public int output() {
            return (int) Math.min(Integer.MAX_VALUE, generation * 4L);
        }
    }

    // <generated by tools/build.py>
    public static final Panel[] ALL = {
            new Panel("grid_panel_grey", false, 0, 8, 0xCDD7DD),
            new Panel("grid_panel_blue", false, 1, 11, 0x0C263E),
            new Panel("grid_panel_indigo", false, 2, 16, 0x232751),
            new Panel("grid_panel_teal", false, 3, 23, 0x00615E),
            new Panel("flare_panel_sunset", false, 4, 33, 0xFB7804),
            new Panel("flare_panel_aurora", false, 5, 46, 0x4EB2FF),
            new Panel("flare_panel_ember", false, 6, 66, 0xC24A77),
            new Panel("flare_panel_glyph", false, 7, 93, 0x9A6595),
            new Panel("flare_panel_amber", false, 8, 132, 0xD3724D),
            new Panel("flare_panel_blaze", false, 9, 188, 0xD58332),
            new Panel("woven_panel_white", false, 10, 267, 0xE6F7F5),
            new Panel("woven_panel_red", false, 11, 379, 0xEC3427),
            new Panel("woven_panel_teal", false, 12, 538, 0x14CCA7),
            new Panel("woven_panel_orange", false, 13, 764, 0xE86B1B),
            new Panel("woven_panel_graphite", false, 14, 1084, 0x7C8A81),
            new Panel("woven_panel_azure", false, 15, 1540, 0x3790E6),
            new Panel("woven_panel_lime", false, 16, 2186, 0x5DBD44),
            new Panel("woven_panel_violet", false, 17, 3105, 0x9944C4),
            new Panel("tearful_panel_sky", false, 18, 4408, 0x469CAC),
            new Panel("tearful_panel_meadow", false, 19, 6260, 0xBDC82C),
            new Panel("tearful_panel_dusk", false, 20, 8889, 0x923DC8),
            new Panel("tearful_panel_sunrise", false, 21, 12622, 0xDB8A19),
            new Panel("tearful_panel_spring", false, 22, 17924, 0xB0C346),
            new Panel("tearful_panel_honey", false, 23, 25452, 0xE1AC21),
            new Panel("tearful_panel_orchid", false, 24, 36142, 0xD846C8),
            new Panel("tearful_panel_twilight", false, 25, 51321, 0x9F6720),
            new Panel("serpent_generator_violet", true, 0, 65536, 0xA88CEE),
            new Panel("serpent_generator_coral", true, 1, 91750, 0xC35453),
            new Panel("serpent_generator_frost", true, 2, 128451, 0xDCDCE6),
            new Panel("serpent_generator_cyan", true, 3, 179831, 0x4DEAE6),
            new Panel("serpent_generator_prism", true, 4, 251763, 0xAEB1DF),
            new Panel("spiral_generator_orange", true, 5, 352468, 0xAE7A4A),
            new Panel("spiral_generator_gold", true, 6, 493456, 0xE9CB62),
            new Panel("spiral_generator_violet", true, 7, 690838, 0x836BC9),
            new Panel("spiral_generator_lavender", true, 8, 967173, 0x7389CA),
            new Panel("spiral_generator_prism", true, 9, 1354042, 0x94D5A7),
            new Panel("meteor_generator_lime", true, 10, 1895659, 0x759838),
            new Panel("meteor_generator_lime2", true, 11, 2653923, 0x8E9248),
            new Panel("meteor_generator_rose", true, 12, 3715492, 0xA04C6A),
            new Panel("meteor_generator_iris", true, 13, 5201689, 0x686BAF),
            new Panel("meteor_generator_magenta", true, 14, 7282365, 0x9D4B9A),
            new Panel("meteor_generator_carnival", true, 15, 10195311, 0x99786A),
            new Panel("core_generator_ice_heart", true, 16, 14273435, 0x6C6BB4),
            new Panel("core_generator_sun_heart", true, 17, 19982809, 0xC56628),
            new Panel("core_generator_ruby", true, 18, 27975933, 0xEA3950),
            new Panel("core_generator_jade", true, 19, 39166306, 0x7990D0),
            new Panel("core_generator_topaz", true, 20, 54832828, 0x8896C8),
            new Panel("core_generator_amethyst", true, 21, 76765959, 0x8285D0),
    };
    // </generated>

    private Panels() {
    }
}
