package com.reya.quantumsolar;

/**
 * Every solar panel and quantum generator, in tier order (built by tools/build.py from
 * reference/panels.jpg, which also draws their textures): id, whether it is a quantum generator,
 * its tier among its kind, what it makes (FE a tick) and its colour (for its GUI).
 */
public final class Panels {
    public record Panel(String id, boolean quantum, int tier, int generation, int colour) {
        /** What it holds: a hundred seconds of making for the panels, ten for the generators (the biggest would not fit otherwise). */
        public int capacity() {
            long c = (long) generation * (quantum ? 200L : 2000L);
            return (int) Math.min(Integer.MAX_VALUE, c);
        }

        /** How much it pushes out a tick, into all its neighbours together. */
        public int output() {
            return (int) Math.min(Integer.MAX_VALUE, generation * 4L);
        }
    }

    // <generated by tools/build.py>
    public static final Panel[] ALL = {
            new Panel("grid_panel_grey", false, 0, 8, 0x767880),
            new Panel("grid_panel_blue", false, 1, 11, 0x3C70A5),
            new Panel("grid_panel_indigo", false, 2, 16, 0x5454B0),
            new Panel("grid_panel_teal", false, 3, 23, 0x1EACA0),
            new Panel("flare_panel_sunset", false, 4, 33, 0xE63C32),
            new Panel("flare_panel_aurora", false, 5, 46, 0x506EE6),
            new Panel("flare_panel_ember", false, 6, 66, 0xDC4646),
            new Panel("flare_panel_glyph", false, 7, 93, 0xAA5ADC),
            new Panel("flare_panel_amber", false, 8, 132, 0xF09628),
            new Panel("flare_panel_blaze", false, 9, 188, 0xFF781E),
            new Panel("woven_panel_white", false, 10, 267, 0xD6DAE0),
            new Panel("woven_panel_red", false, 11, 379, 0xD6342C),
            new Panel("woven_panel_teal", false, 12, 538, 0x1CB094),
            new Panel("woven_panel_orange", false, 13, 764, 0xEC7622),
            new Panel("woven_panel_graphite", false, 14, 1084, 0x686C6E),
            new Panel("woven_panel_azure", false, 15, 1540, 0x50A8EC),
            new Panel("woven_panel_lime", false, 16, 2186, 0x76CE34),
            new Panel("woven_panel_violet", false, 17, 3105, 0xA64EDA),
            new Panel("tearful_panel_sky", false, 18, 4408, 0x5AC8F0),
            new Panel("tearful_panel_meadow", false, 19, 6260, 0xB4DC3C),
            new Panel("tearful_panel_dusk", false, 20, 8889, 0xC86EE6),
            new Panel("tearful_panel_sunrise", false, 21, 12622, 0xFFBE46),
            new Panel("tearful_panel_spring", false, 22, 17924, 0x78E6A0),
            new Panel("tearful_panel_honey", false, 23, 25452, 0xFAC83C),
            new Panel("tearful_panel_orchid", false, 24, 36142, 0xF06ED2),
            new Panel("tearful_panel_twilight", false, 25, 51321, 0x8C6EF0),
            new Panel("serpent_generator_violet", true, 0, 65536, 0x9664FF),
            new Panel("serpent_generator_coral", true, 1, 91750, 0xFF6464),
            new Panel("serpent_generator_frost", true, 2, 128451, 0xBEE1FF),
            new Panel("serpent_generator_cyan", true, 3, 179831, 0x28DCE6),
            new Panel("serpent_generator_prism", true, 4, 251763, 0xFF78C8),
            new Panel("spiral_generator_orange", true, 5, 352468, 0xFF8C28),
            new Panel("spiral_generator_gold", true, 6, 493456, 0xFFC832),
            new Panel("spiral_generator_violet", true, 7, 690838, 0x966EFF),
            new Panel("spiral_generator_lavender", true, 8, 967173, 0xAABEFF),
            new Panel("spiral_generator_prism", true, 9, 1354042, 0xFFA03C),
            new Panel("meteor_generator_lime", true, 10, 1895659, 0xAADC32),
            new Panel("meteor_generator_lime2", true, 11, 2653923, 0xD2D750),
            new Panel("meteor_generator_rose", true, 12, 3715492, 0xF05A8C),
            new Panel("meteor_generator_iris", true, 13, 5201689, 0x9678FF),
            new Panel("meteor_generator_magenta", true, 14, 7282365, 0xE650DC),
            new Panel("meteor_generator_carnival", true, 15, 10195311, 0xFF64A0),
            new Panel("core_generator_ice_heart", true, 16, 14273435, 0x78DCEB),
            new Panel("core_generator_sun_heart", true, 17, 19982809, 0xF59632),
            new Panel("core_generator_ruby", true, 18, 27975933, 0xE13246),
            new Panel("core_generator_jade", true, 19, 39166306, 0x3CCD96),
            new Panel("core_generator_topaz", true, 20, 54832828, 0xF5BE3C),
            new Panel("core_generator_amethyst", true, 21, 76765959, 0xB464F5),
    };
    // </generated>

    private Panels() {
    }
}
