org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
neo_version=47.1.106
neo_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=multibrewer
mod_name=Multi Brewer
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.reya.multibrewer
mod_authors=Reya
mod_description=Multi Brewer: mix up to three potions into one, stretch their duration with redstone and raise their power with glowstone past the vanilla limits. Speed, efficiency and potency upgrades.
